"""
Report model for the defect management system.

This module defines the Report model with its relationships,
constraints, and indexes as specified in the requirements.
"""

from datetime import datetime, timezone
from typing import TYPE_CHECKING

from sqlalchemy import String, Integer, DateTime, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base

if TYPE_CHECKING:
    from app.models.project import Project
    from app.models.user import User


class Report(Base):
    """
    Report model representing generated analytical reports.
    
    Reports are generated by managers for specific projects and can be
    of different types (e.g., "by status", "by assignee").
    The file_path stores the location of the generated CSV or XLSX file.
    
    Requirements: 10.1-10.5, 11.12
    """
    __tablename__ = "reports"
    
    # Primary key
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    
    # Project relationship
    project_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("projects.id", ondelete="RESTRICT"),
        nullable=False,
        index=True
    )
    
    # Report information
    report_type: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    
    # Generator relationship
    generated_by: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
        index=True
    )
    
    # File path to the generated report
    file_path: Mapped[str] = mapped_column(String(512), nullable=False)
    
    # Timestamp
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
        index=True
    )
    
    # Relationships
    project: Mapped["Project"] = relationship(
        "Project",
        back_populates="reports",
        lazy="select"
    )
    
    generator: Mapped["User"] = relationship(
        "User",
        back_populates="generated_reports",
        lazy="select"
    )
    
    def __repr__(self) -> str:
        return f"<Report(id={self.id}, project_id={self.project_id}, report_type='{self.report_type}')>"
